name: Daily Delaware Probate Scraper

on:
  schedule:
    # Run every day at 8:00 AM UTC (3:00 AM EST)
    - cron: '30 14 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run the scraper
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        python scrape_delaware_daily.py

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          github.rest.issues.create({
            owner,
            repo,
            title: 'Daily Delaware Probate Scraper Failed',
            body: 'The daily scrape failed. Please check the logs.',
            labels: ['failure']
          });
